"""Robot and scene assets supplied by WASMAN."""

from .bluerov2_alpha import (
    BLUEROV2_ALPHA_ARM_JOINT_NAMES,
    BLUEROV2_ALPHA_BODY_NAMES,
    BLUEROV2_ALPHA_CFG,
    BLUEROV2_ALPHA_GRIPPER_JOINT_NAME,
    BLUEROV2_ALPHA_HYDRODYNAMICS,
)

__all__ = [
    "BLUEROV2_ALPHA_ARM_JOINT_NAMES",
    "BLUEROV2_ALPHA_BODY_NAMES",
    "BLUEROV2_ALPHA_CFG",
    "BLUEROV2_ALPHA_GRIPPER_JOINT_NAME",
    "BLUEROV2_ALPHA_HYDRODYNAMICS",
]
